# This is a Jinja2 compatible Dockerfile template
FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f46container FGC=f46 FBR=f46
ADD fedora-20260830.tar /
CMD ["/bin/bash"]