# This is a Jinja2 compatible Dockerfile template
FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=rawhidecontainer FGC=rawhide FBR=rawhide
ADD layer.tar /
CMD ["/bin/bash"]