FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"                    
ENV DISTTAG=fRawhidecontainer FGC=fRawhide FBR=fRawhide
ADD fedora-Rawhide.20210426-s390x.tar.xz / 
CMD ["/bin/bash"]