# This is a Jinja2 compatible Dockerfile template
FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f42container FGC=f42 FBR=f42
ADD fedora-20241208.tar /
CMD ["/bin/bash"]