# This is a Jinja2 compatible Dockerfile template
FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f40container FGC=f40 FBR=f40
ADD fedora-20241013.tar /
CMD ["/bin/bash"]