# This is a Jinja2 compatible Dockerfile template
FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f41container FGC=f41 FBR=f41
ADD fedora-20250602.tar /
CMD ["/bin/bash"]