# This is a Jinja2 compatible Dockerfile template
FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f45container FGC=f45 FBR=f45
ADD fedora-20260222.tar /
CMD ["/bin/bash"]