FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"                    
ENV DISTTAG=fRawhidecontainer FGC=fRawhide FBR=fRawhide
ADD fedora-Rawhide.20210426-x86_64.tar.xz / 
CMD ["/bin/bash"]